<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Backdrop extends Model
{
    use Sushi;

    protected $rows = [
        [
            'slug' => 'office',
            'name' => 'Office',
            'prompt' => 'standing in a professional office workspace',
            'male_preview_path' => '/styles/backdrops/office-men.webp',
            'female_preview_path' => '/styles/backdrops/office-women.webp',
        ],
        [
            'slug' => 'window',
            'name' => 'Window',
            'prompt' => 'standing near a large window with natural light',
            'male_preview_path' => '/styles/backdrops/window-men.webp',
            'female_preview_path' => '/styles/backdrops/window-women.webp',
        ],
        [
            'slug' => 'cafe',
            'name' => 'Cafe',
            'prompt' => 'standing in a cozy cafe setting',
            'male_preview_path' => '/styles/backdrops/cafe-men.webp',
            'female_preview_path' => '/styles/backdrops/cafe-women.webp',
        ],
        [
            'slug' => 'bookshelf',
            'name' => 'Bookshelf',
            'prompt' => 'standing in front of a bookshelf',
            'male_preview_path' => '/styles/backdrops/bookshelf-men.webp',
            'female_preview_path' => '/styles/backdrops/bookshelf-women.webp',
        ],
        [
            'slug' => 'public-speaking',
            'name' => 'Public Speaking',
            'prompt' => 'standing addressing an audience in a ted talk like setting',
            'male_preview_path' => '/styles/backdrops/public-speaking-men.webp',
            'female_preview_path' => '/styles/backdrops/public-speaking-women.webp',
        ],
        [
            'slug' => 'data-center',
            'name' => 'Data Center',
            'prompt' => 'standing in a high-tech data center environment',
            'male_preview_path' => '/styles/backdrops/data-center-men.webp',
            'female_preview_path' => '/styles/backdrops/data-center-women.webp',
        ],
        [
            'slug' => 'colorful-swirls',
            'name' => 'Colorful Swirls',
            'prompt' => 'standing against a vibrant, abstract colorful background',
            'male_preview_path' => '/styles/backdrops/colorful-swirls-men.webp',
            'female_preview_path' => '/styles/backdrops/colorful-swirls-women.webp',
        ],
        [
            'slug' => 'building',
            'name' => 'Building',
            'prompt' => 'standing outside a modern building with large windows, natural light, and a blurred background',
            'male_preview_path' => '/styles/backdrops/building-men.webp',
            'female_preview_path' => '/styles/backdrops/building-women.webp',
        ],
        [
            'slug' => 'grey',
            'name' => 'Grey',
            'prompt' => 'standing against a plain dark gray background',
            'male_preview_path' => '/styles/backdrops/grey-men.webp',
            'female_preview_path' => '/styles/backdrops/grey-women.webp',
        ],
        [
            'slug' => 'lobby',
            'name' => 'Lobby',
            'prompt' => 'standing in a modern office with large windows, natural light, and a blurred background',
            'male_preview_path' => '/styles/backdrops/lobby-men.webp',
            'female_preview_path' => '/styles/backdrops/lobby-women.webp',
        ],
        [
            'slug' => 'white',
            'name' => 'White',
            'prompt' => 'standing against a clean white background',
            'male_preview_path' => '/styles/backdrops/white-men.webp',
            'female_preview_path' => '/styles/backdrops/white-women.webp',
        ],
        [
            'slug' => 'garden',
            'name' => 'Garden',
            'prompt' => 'standing in a lush garden setting',
            'male_preview_path' => '/styles/backdrops/garden-men.webp',
            'female_preview_path' => '/styles/backdrops/garden-women.webp',
        ],
        [
            'slug' => 'lush-greenery',
            'name' => 'Lush Greenery',
            'prompt' => 'standing surrounded by dense greenery',
            'male_preview_path' => '/styles/backdrops/lush-greenery-men.webp',
            'female_preview_path' => '/styles/backdrops/lush-greenery-women.webp',
        ],
        [
            'slug' => 'neutral-gradient',
            'name' => 'Neutral Gradient',
            'prompt' => 'standing against a soft neutral gradient background',
            'male_preview_path' => '/styles/backdrops/neutral-gradient-men.webp',
            'female_preview_path' => '/styles/backdrops/neutral-gradient-women.webp',
        ],
        [
            'slug' => 'grey-light-grey',
            'name' => 'Grey Light Grey',
            'prompt' => 'standing against a light grey background',
            'male_preview_path' => '/styles/backdrops/grey-light-grey-men.webp',
            'female_preview_path' => '/styles/backdrops/grey-light-grey-women.webp',
        ],
        [
            'slug' => 'gray-texture',
            'name' => 'Gray Texture',
            'prompt' => 'standing against a textured gray background',
            'male_preview_path' => '/styles/backdrops/gray-texture-men.webp',
            'female_preview_path' => '/styles/backdrops/gray-texture-women.webp',
        ],
        [
            'slug' => 'office-workspace',
            'name' => 'Office Workspace',
            'prompt' => 'standing in a modern office workspace',
            'male_preview_path' => '/styles/backdrops/office-workspace-men.webp',
            'female_preview_path' => '/styles/backdrops/office-workspace-women.webp',
        ],
        [
            'slug' => 'dark',
            'name' => 'Dark',
            'prompt' => 'standing against a dark background',
            'male_preview_path' => '/styles/backdrops/dark-men.webp',
            'female_preview_path' => '/styles/backdrops/dark-women.webp',
        ],
        [
            'slug' => 'loft-interior',
            'name' => 'Loft Interior',
            'prompt' => 'standing in a stylish loft interior',
            'male_preview_path' => '/styles/backdrops/loft-interior-men.webp',
            'female_preview_path' => '/styles/backdrops/loft-interior-women.webp',
        ],
        [
            'slug' => 'park',
            'name' => 'Park',
            'prompt' => 'standing in a serene park setting',
            'male_preview_path' => '/styles/backdrops/park-men.webp',
            'female_preview_path' => '/styles/backdrops/park-women.webp',
        ],
        [
            'slug' => 'french-rooftop',
            'name' => 'French Rooftop',
            'prompt' => 'standing on a charming French rooftop',
            'male_preview_path' => '/styles/backdrops/french-rooftop-men.webp',
            'female_preview_path' => '/styles/backdrops/french-rooftop-women.webp',
        ],
        [
            'slug' => 'red-brick',
            'name' => 'Red Brick',
            'prompt' => 'standing against a red brick wall',
            'male_preview_path' => '/styles/backdrops/red-brick-men.webp',
            'female_preview_path' => '/styles/backdrops/red-brick-women.webp',
        ],
        [
            'slug' => 'streets',
            'name' => 'Streets',
            'prompt' => 'standing on a lively urban street',
            'male_preview_path' => '/styles/backdrops/streets-men.webp',
            'female_preview_path' => '/styles/backdrops/streets-women.webp',
        ],
        [
            'slug' => 'urban-sunlight',
            'name' => 'Urban Sunlight',
            'prompt' => 'standing bathed in urban sunlight',
            'male_preview_path' => '/styles/backdrops/urban-sunlight-men.webp',
            'female_preview_path' => '/styles/backdrops/urban-sunlight-women.webp',
        ],
        [
            'slug' => 'office-screens',
            'name' => 'Office Screens',
            'prompt' => 'standing in front of office screens',
            'male_preview_path' => '/styles/backdrops/office-screens-men.webp',
            'female_preview_path' => '/styles/backdrops/office-screens-women.webp',
        ],
        [
            'slug' => 'rustic-wood',
            'name' => 'Rustic Wood',
            'prompt' => 'standing against a rustic wood background',
            'male_preview_path' => '/styles/backdrops/rustic-wood-men.webp',
            'female_preview_path' => '/styles/backdrops/rustic-wood-women.webp',
        ],
        [
            'slug' => 'muted-nature',
            'name' => 'Muted Nature',
            'prompt' => 'standing in a muted nature setting',
            'male_preview_path' => '/styles/backdrops/muted-nature-men.webp',
            'female_preview_path' => '/styles/backdrops/muted-nature-women.webp',
        ],
        [
            'slug' => 'hotel',
            'name' => 'Hotel',
            'prompt' => 'standing in an elegant hotel lobby',
            'male_preview_path' => '/styles/backdrops/hotel-men.webp',
            'female_preview_path' => '/styles/backdrops/hotel-women.webp',
        ],
        [
            'slug' => 'beach-sunrise',
            'name' => 'Beach Sunrise',
            'prompt' => 'standing at a beach during sunrise',
            'male_preview_path' => '/styles/backdrops/beach-sunrise-men.webp',
            'female_preview_path' => '/styles/backdrops/beach-sunrise-women.webp',
        ],
        [
            'slug' => 'woods',
            'name' => 'Woods',
            'prompt' => 'standing in a dense woodland',
            'male_preview_path' => '/styles/backdrops/woods-men.webp',
            'female_preview_path' => '/styles/backdrops/woods-women.webp',
        ],
        [
            'slug' => 'realtor',
            'name' => 'Realtor',
            'prompt' => 'standing outside a house as a real estate setting',
            'male_preview_path' => '/styles/backdrops/realtor-men.webp',
            'female_preview_path' => '/styles/backdrops/realtor-women.webp',
        ],
        [
            'slug' => 'plain-pastel-blue',
            'name' => 'Plain Pastel Blue',
            'prompt' => 'standing against a plain pastel blue background',
            'male_preview_path' => '/styles/backdrops/plain-pastel-blue-men.webp',
            'female_preview_path' => '/styles/backdrops/plain-pastel-blue-women.webp',
        ],
        [
            'slug' => 'marina',
            'name' => 'Marina',
            'prompt' => 'standing at a marina with boats',
            'male_preview_path' => '/styles/backdrops/marina-men.webp',
            'female_preview_path' => '/styles/backdrops/marina-women.webp',
        ],
        [
            'slug' => 'lake',
            'name' => 'Lake',
            'prompt' => 'standing by a tranquil lake',
            'male_preview_path' => '/styles/backdrops/lake-men.webp',
            'female_preview_path' => '/styles/backdrops/lake-women.webp',
        ],
        [
            'slug' => 'alley',
            'name' => 'Alley',
            'prompt' => 'standing in a narrow urban alley',
            'male_preview_path' => '/styles/backdrops/alley-men.webp',
            'female_preview_path' => '/styles/backdrops/alley-women.webp',
        ],
        [
            'slug' => 'sky-blue-with-pattern',
            'name' => 'Sky Blue With Pattern',
            'prompt' => 'standing against a sky blue patterned background',
            'male_preview_path' => '/styles/backdrops/sky-blue-with-pattern-men.webp',
            'female_preview_path' => '/styles/backdrops/sky-blue-with-pattern-women.webp',
        ],
        [
            'slug' => 'azure-blue',
            'name' => 'Azure Blue',
            'prompt' => 'standing against an azure blue background',
            'male_preview_path' => '/styles/backdrops/azure-blue-men.webp',
            'female_preview_path' => '/styles/backdrops/azure-blue-women.webp',
        ],
        [
            'slug' => 'upscale-nyc-bar',
            'name' => 'Upscale NYC Bar',
            'prompt' => 'standing in an upscale New York City bar',
            'male_preview_path' => '/styles/backdrops/upscale-nyc-bar-men.webp',
            'female_preview_path' => '/styles/backdrops/upscale-nyc-bar-women.webp',
        ],
        [
            'slug' => 'server-room',
            'name' => 'Server Room',
            'prompt' => 'standing in a high-tech server room',
            'male_preview_path' => '/styles/backdrops/server-room-men.webp',
            'female_preview_path' => '/styles/backdrops/server-room-women.webp',
        ],
        [
            'slug' => 'blue',
            'name' => 'Blue',
            'prompt' => 'standing against a solid blue background',
            'male_preview_path' => '/styles/backdrops/blue-men.webp',
            'female_preview_path' => '/styles/backdrops/blue-women.webp',
        ],
        [
            'slug' => 'sunset',
            'name' => 'Sunset',
            'prompt' => 'standing during a beautiful sunset',
            'male_preview_path' => '/styles/backdrops/sunset-men.webp',
            'female_preview_path' => '/styles/backdrops/sunset-women.webp',
        ],
        [
            'slug' => 'rustic-charm',
            'name' => 'Rustic Charm',
            'prompt' => 'standing in a rustic charming setting',
            'male_preview_path' => '/styles/backdrops/rustic-charm-men.webp',
            'female_preview_path' => '/styles/backdrops/rustic-charm-women.webp',
        ],
        [
            'slug' => 'beach-stairs',
            'name' => 'Beach Stairs',
            'prompt' => 'standing on stairs leading to a beach',
            'male_preview_path' => '/styles/backdrops/beach-stairs-men.webp',
            'female_preview_path' => '/styles/backdrops/beach-stairs-women.webp',
        ],
        [
            'slug' => 'green',
            'name' => 'Green',
            'prompt' => 'standing against a solid green background',
            'male_preview_path' => '/styles/backdrops/green-men.webp',
            'female_preview_path' => '/styles/backdrops/green-women.webp',
        ],
        [
            'slug' => 'tulips',
            'name' => 'Tulips',
            'prompt' => 'standing surrounded by tulips',
            'male_preview_path' => '/styles/backdrops/tulips-men.webp',
            'female_preview_path' => '/styles/backdrops/tulips-women.webp',
        ],
        [
            'slug' => 'fence',
            'name' => 'Fence',
            'prompt' => 'standing against a wooden fence',
            'male_preview_path' => '/styles/backdrops/fence-men.webp',
            'female_preview_path' => '/styles/backdrops/fence-women.webp',
        ],
        [
            'slug' => 'earthy-textures',
            'name' => 'Earthy Textures',
            'prompt' => 'standing against earthy textured backgrounds',
            'male_preview_path' => '/styles/backdrops/earthy-textures-men.webp',
            'female_preview_path' => '/styles/backdrops/earthy-textures-women.webp',
        ],
        [
            'slug' => 'brooklyn-waterfront',
            'name' => 'Brooklyn Waterfront',
            'prompt' => 'standing along the Brooklyn waterfront',
            'male_preview_path' => '/styles/backdrops/brooklyn-waterfront-men.webp',
            'female_preview_path' => '/styles/backdrops/brooklyn-waterfront-women.webp',
        ],
        [
            'slug' => 'kitchen',
            'name' => 'Kitchen',
            'prompt' => 'standing in a modern kitchen',
            'male_preview_path' => '/styles/backdrops/kitchen-men.webp',
            'female_preview_path' => '/styles/backdrops/kitchen-women.webp',
        ],
        [
            'slug' => 'wildflower-field',
            'name' => 'Wildflower Field',
            'prompt' => 'standing in a field of wildflowers',
            'male_preview_path' => '/styles/backdrops/wildflower-field-men.webp',
            'female_preview_path' => '/styles/backdrops/wildflower-field-women.webp',
        ],
        [
            'slug' => 'yellow-brick',
            'name' => 'Yellow Brick',
            'prompt' => 'standing against a yellow brick wall',
            'male_preview_path' => '/styles/backdrops/yellow-brick-men.webp',
            'female_preview_path' => '/styles/backdrops/yellow-brick-women.webp',
        ],
        [
            'slug' => 'yellow',
            'name' => 'Yellow',
            'prompt' => 'standing against a solid yellow background',
            'male_preview_path' => '/styles/backdrops/yellow-men.webp',
            'female_preview_path' => '/styles/backdrops/yellow-women.webp',
        ],
        [
            'slug' => 'cozy-christmas',
            'name' => 'Cozy Christmas',
            'prompt' => 'standing in a cozy Christmas setting',
            'male_preview_path' => '/styles/backdrops/cozy-christmas-men.webp',
            'female_preview_path' => '/styles/backdrops/cozy-christmas-women.webp',
        ],
        [
            'slug' => 'light-salmon-pink',
            'name' => 'Light Salmon Pink',
            'prompt' => 'standing against a light salmon pink background',
            'male_preview_path' => '/styles/backdrops/light-salmon-pink-men.webp',
            'female_preview_path' => '/styles/backdrops/light-salmon-pink-women.webp',
        ],
        [
            'slug' => 'soft-marigold-gold',
            'name' => 'Soft Marigold Gold',
            'prompt' => 'standing against a soft marigold gold background',
            'male_preview_path' => '/styles/backdrops/soft-marigold-gold-men.webp',
            'female_preview_path' => '/styles/backdrops/soft-marigold-gold-women.webp',
        ],
    ];
}
