<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Outfit extends Model
{
    use Sushi;

    protected $rows = [
        [
            'slug' => 'fitted-black-turtleneck-men',
            'name' => 'cuello tortuga negro ajustado',
            'prompt' => 'wearing a fitted black turtleneck',
            'preview_path' => '/styles/outfits/fitted-black-turtleneck-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'fitted-black-turtleneck-women',
            'name' => 'cuello tortuga negro ajustado',
            'prompt' => 'wearing a fitted black turtleneck',
            'preview_path' => '/styles/outfits/fitted-black-turtleneck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'monochromatic-taupe-suit-with-white-top-women',
            'name' => 'traje beige monocromático con blusa blanca',
            'prompt' => 'wearing a monochromatic taupe suit with white top',
            'preview_path' => '/styles/outfits/monochromatic-taupe-suit-with-white-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blue-sleeveless-dress-women',
            'name' => 'vestido azul marino sin mangas',
            'prompt' => 'wearing a navy blue sleeveless dress',
            'preview_path' => '/styles/outfits/navy-blue-sleeveless-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'classic-navy-pantsuit-with-white-blouse-women',
            'name' => 'traje pantalón azul marino clásico con blusa blanca',
            'prompt' => 'wearing a classic navy pantsuit with white blouse',
            'preview_path' => '/styles/outfits/classic-navy-pantsuit-with-white-blouse-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'burgundy-blazer-over-white-tee-women',
            'name' => 'saco borgoña sobre playera blanca',
            'prompt' => 'wearing a burgundy blazer over white t-shirt',
            'preview_path' => '/styles/outfits/burgundy-blazer-over-white-tee-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-tuxedo-jacket-men',
            'name' => 'chaqueta de esmoquin negro',
            'prompt' => 'wearing a black tuxedo jacket',
            'preview_path' => '/styles/outfits/black-tuxedo-jacket-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-blazer-with-light-blue-shirt-men',
            'name' => 'saco azul marino con camisa azul claro',
            'prompt' => 'wearing a navy blazer with light blue shirt',
            'preview_path' => '/styles/outfits/navy-blazer-with-light-blue-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-blazer-with-light-blue-shirt-women',
            'name' => 'saco azul marino con camisa azul claro',
            'prompt' => 'wearing a navy blazer with light blue shirt',
            'preview_path' => '/styles/outfits/navy-blazer-with-light-blue-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-long-sleeve-button-up-shirt-men',
            'name' => 'camisa negra de manga larga con botones',
            'prompt' => 'wearing a black long-sleeve button-up shirt',
            'preview_path' => '/styles/outfits/black-long-sleeve-button-up-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-long-sleeve-button-up-shirt-women',
            'name' => 'camisa negra de manga larga con botones',
            'prompt' => 'wearing a black long-sleeve button-up shirt',
            'preview_path' => '/styles/outfits/black-long-sleeve-button-up-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-gray-patterned-blazer-men',
            'name' => 'saco gris oscuro con estampado',
            'prompt' => 'wearing a dark gray patterned blazer',
            'preview_path' => '/styles/outfits/dark-gray-patterned-blazer-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-gray-patterned-blazer-women',
            'name' => 'saco gris oscuro con estampado',
            'prompt' => 'wearing a dark gray patterned blazer',
            'preview_path' => '/styles/outfits/dark-gray-patterned-blazer-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-blue-suit-jacket-men',
            'name' => 'saco de traje azul oscuro',
            'prompt' => 'wearing a dark blue suit jacket',
            'preview_path' => '/styles/outfits/dark-blue-suit-jacket-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-button-up-shirt-men',
            'name' => 'camisa blanca de botones',
            'prompt' => 'wearing a white button-up shirt',
            'preview_path' => '/styles/outfits/white-button-up-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-button-up-shirt-women',
            'name' => 'camisa blanca de botones',
            'prompt' => 'wearing a white button-up shirt',
            'preview_path' => '/styles/outfits/white-button-up-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blue-crew-neck-sweater-men',
            'name' => 'suéter azul marino de cuello redondo',
            'prompt' => 'wearing a navy blue crew-neck sweater',
            'preview_path' => '/styles/outfits/navy-blue-crew-neck-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-blue-tailored-suit-men',
            'name' => 'traje azul oscuro a la medida',
            'prompt' => 'wearing a dark blue tailored suit',
            'preview_path' => '/styles/outfits/dark-blue-tailored-suit-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-blue-tailored-suit-women',
            'name' => 'traje azul oscuro a la medida',
            'prompt' => 'wearing a dark blue tailored suit',
            'preview_path' => '/styles/outfits/dark-blue-tailored-suit-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-blue-blazer-over-a-white-shirt-men',
            'name' => 'saco azul oscuro sobre camisa blanca',
            'prompt' => 'wearing a dark blue blazer over a white shirt',
            'preview_path' => '/styles/outfits/dark-blue-blazer-over-a-white-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-blue-blazer-over-a-white-shirt-women',
            'name' => 'saco azul oscuro sobre camisa blanca',
            'prompt' => 'wearing a dark blue blazer over a white shirt',
            'preview_path' => '/styles/outfits/dark-blue-blazer-over-a-white-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-blazer-over-black-top-women',
            'name' => 'saco negro sobre top negro',
            'prompt' => 'wearing a black blazer over black top',
            'preview_path' => '/styles/outfits/black-blazer-over-black-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-ribbed-half-zip-sweater-men',
            'name' => 'suéter gris claro acanalado con medio cierre',
            'prompt' => 'wearing a light gray ribbed half-zip sweater',
            'preview_path' => '/styles/outfits/light-gray-ribbed-half-zip-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-v-neck-sweater-men',
            'name' => 'suéter negro con escote en V',
            'prompt' => 'wearing a black v-neck sweater',
            'preview_path' => '/styles/outfits/black-v-neck-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-v-neck-sweater-women',
            'name' => 'suéter negro con escote en V',
            'prompt' => 'wearing a black v-neck sweater',
            'preview_path' => '/styles/outfits/black-v-neck-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-suit-ensemble-men',
            'name' => 'conjunto de traje gris claro',
            'prompt' => 'wearing a light gray suit ensemble',
            'preview_path' => '/styles/outfits/light-gray-suit-ensemble-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-gray-suit-ensemble-women',
            'name' => 'conjunto de traje gris claro',
            'prompt' => 'wearing a light gray suit ensemble',
            'preview_path' => '/styles/outfits/light-gray-suit-ensemble-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'coral-blazer-over-white-blouse-women',
            'name' => 'saco coral sobre blusa blanca',
            'prompt' => 'wearing a coral blazer over white blouse',
            'preview_path' => '/styles/outfits/coral-blazer-over-white-blouse-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'ribbed-navy-sweater-men',
            'name' => 'suéter azul marino acanalado',
            'prompt' => 'wearing a ribbed navy sweater',
            'preview_path' => '/styles/outfits/ribbed-navy-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'ribbed-navy-sweater-women',
            'name' => 'suéter azul marino acanalado',
            'prompt' => 'wearing a ribbed navy sweater',
            'preview_path' => '/styles/outfits/ribbed-navy-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'camel-double-breasted-coat-women',
            'name' => 'abrigo camel de doble botonadura',
            'prompt' => 'wearing a camel double-breasted coat',
            'preview_path' => '/styles/outfits/camel-double-breasted-coat-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blue-short-sleeve-polo-men',
            'name' => 'polo azul marino de manga corta',
            'prompt' => 'wearing a navy blue short-sleeve polo',
            'preview_path' => '/styles/outfits/navy-blue-short-sleeve-polo-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-blue-short-sleeve-polo-women',
            'name' => 'polo azul marino de manga corta',
            'prompt' => 'wearing a navy blue short-sleeve polo',
            'preview_path' => '/styles/outfits/navy-blue-short-sleeve-polo-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-crewneck-t-shirt-men',
            'name' => 'playera negra de cuello redondo',
            'prompt' => 'wearing a black crewneck t-shirt',
            'preview_path' => '/styles/outfits/black-crewneck-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-sheath-dress-women',
            'name' => 'vestido blanco ajustado',
            'prompt' => 'wearing a white sheath dress',
            'preview_path' => '/styles/outfits/white-sheath-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blazer-over-burgundy-sweater-women',
            'name' => 'saco azul marino sobre suéter borgoña',
            'prompt' => 'wearing a navy blazer over burgundy sweater',
            'preview_path' => '/styles/outfits/navy-blazer-over-burgundy-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'charcoal-gray-blazer-with-light-blue-button-up-shirt-men',
            'name' => 'saco gris carbón con camisa azul claro de botones',
            'prompt' => 'wearing a charcoal gray blazer with light blue button up shirt',
            'preview_path' => '/styles/outfits/charcoal-gray-blazer-with-light-blue-button-up-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'charcoal-gray-blazer-with-light-blue-button-up-shirt-women',
            'name' => 'saco gris carbón con camisa azul claro de botones',
            'prompt' => 'wearing a charcoal gray blazer with light blue button up shirt',
            'preview_path' => '/styles/outfits/charcoal-gray-blazer-with-light-blue-button-up-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-denim-jacket-women',
            'name' => 'chaqueta de mezclilla azul claro',
            'prompt' => 'wearing a light blue denim jacket',
            'preview_path' => '/styles/outfits/light-blue-denim-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-denim-jacket-men',
            'name' => 'chaqueta de mezclilla azul claro',
            'prompt' => 'wearing a light blue denim jacket',
            'preview_path' => '/styles/outfits/light-blue-denim-jacket-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-gray-blazer-men',
            'name' => 'saco gris claro',
            'prompt' => 'wearing a light gray blazer',
            'preview_path' => '/styles/outfits/light-gray-blazer-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-gray-cardigan-women',
            'name' => 'cárdigan gris claro',
            'prompt' => 'wearing a light gray cardigan',
            'preview_path' => '/styles/outfits/light-gray-cardigan-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-cardigan-men',
            'name' => 'cárdigan gris claro',
            'prompt' => 'wearing a light gray cardigan',
            'preview_path' => '/styles/outfits/light-gray-cardigan-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-ribbed-v-neck-sweater-women',
            'name' => 'suéter negro acanalado con escote en V',
            'prompt' => 'wearing a black ribbed v-neck sweater',
            'preview_path' => '/styles/outfits/black-ribbed-v-neck-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blazer-over-white-button-up-shirt-women',
            'name' => 'saco azul marino sobre camisa blanca de botones',
            'prompt' => 'wearing a navy blazer over white button-up shirt',
            'preview_path' => '/styles/outfits/navy-blazer-over-white-button-up-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blazer-over-white-button-up-shirt-men',
            'name' => 'saco azul marino sobre camisa blanca de botones',
            'prompt' => 'wearing a navy blazer over white button-up shirt',
            'preview_path' => '/styles/outfits/navy-blazer-over-white-button-up-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-t-shirt-and-black-trousers-women',
            'name' => 'playera blanca y pantalones negros',
            'prompt' => 'wearing a white t-shirt and black trousers',
            'preview_path' => '/styles/outfits/white-t-shirt-and-black-trousers-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-t-shirt-and-black-trousers-men',
            'name' => 'playera blanca y pantalones negros',
            'prompt' => 'wearing a white t-shirt and black trousers',
            'preview_path' => '/styles/outfits/white-t-shirt-and-black-trousers-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'blue-and-white-checked-button-up-men',
            'name' => 'camisa de botones a cuadros azul y blanco',
            'prompt' => 'wearing a blue and white checked button-up',
            'preview_path' => '/styles/outfits/blue-and-white-checked-button-up-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'caramel-ribbed-knit-sweater-and-black-pleated-skirt-women',
            'name' => 'suéter acanalado caramelo y falda plisada negra',
            'prompt' => 'wearing a caramel ribbed knit sweater and black pleated skirt',
            'preview_path' => '/styles/outfits/caramel-ribbed-knit-sweater-and-black-pleated-skirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'maroon-button-down-shirt-men',
            'name' => 'camisa de botones granate',
            'prompt' => 'wearing a maroon button down shirt',
            'preview_path' => '/styles/outfits/maroon-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'maroon-button-down-shirt-women',
            'name' => 'camisa de botones granate',
            'prompt' => 'wearing a maroon button down shirt',
            'preview_path' => '/styles/outfits/maroon-button-down-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-ribbed-turtleneck-women',
            'name' => 'cuello tortuga acanalado gris claro',
            'prompt' => 'wearing a light gray ribbed turtleneck',
            'preview_path' => '/styles/outfits/light-gray-ribbed-turtleneck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-ribbed-turtleneck-men',
            'name' => 'cuello tortuga acanalado gris claro',
            'prompt' => 'wearing a light gray ribbed turtleneck',
            'preview_path' => '/styles/outfits/light-gray-ribbed-turtleneck-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'ribbed-beige-sweater-women',
            'name' => 'suéter beige acanalado',
            'prompt' => 'wearing a ribbed beige sweater',
            'preview_path' => '/styles/outfits/ribbed-beige-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'ribbed-beige-sweater-men',
            'name' => 'suéter beige acanalado',
            'prompt' => 'wearing a ribbed beige sweater',
            'preview_path' => '/styles/outfits/ribbed-beige-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-green-blazer-outfit-women',
            'name' => 'conjunto de saco verde oscuro',
            'prompt' => 'wearing a dark green blazer outfit',
            'preview_path' => '/styles/outfits/dark-green-blazer-outfit-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-green-blazer-outfit-men',
            'name' => 'conjunto de saco verde oscuro',
            'prompt' => 'wearing a dark green blazer outfit',
            'preview_path' => '/styles/outfits/dark-green-blazer-outfit-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'high-waisted-trousers-with-a-white-blouse-women',
            'name' => 'pantalones de tiro alto con blusa blanca',
            'prompt' => 'wearing high-waisted trousers with a white blouse',
            'preview_path' => '/styles/outfits/high-waisted-trousers-with-a-white-blouse-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-relaxed-fit-balloon-sleeve-top-women',
            'name' => 'top negro holgado con mangas globo',
            'prompt' => 'wearing a black relaxed-fit balloon sleeve top',
            'preview_path' => '/styles/outfits/black-relaxed-fit-balloon-sleeve-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-relaxed-fit-balloon-sleeve-top-men',
            'name' => 'top negro holgado con mangas globo',
            'prompt' => 'wearing a black relaxed-fit balloon sleeve top',
            'preview_path' => '/styles/outfits/black-relaxed-fit-balloon-sleeve-top-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-short-sleeve-knit-top-and-cream-high-waisted-trousers-women',
            'name' => 'top negro de manga corta y pantalones crema de tiro alto',
            'prompt' => 'wearing a black short-sleeve knit top and cream high-waisted trousers',
            'preview_path' => '/styles/outfits/black-short-sleeve-knit-top-and-cream-high-waisted-trousers-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-button-up-women',
            'name' => 'camisa azul claro de botones',
            'prompt' => 'wearing a light blue button-up',
            'preview_path' => '/styles/outfits/light-blue-button-up-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'pink-rose-blazer-with-cream-top-and-skirt-women',
            'name' => 'saco rosa con top crema y falda',
            'prompt' => 'wearing a pink rose blazer with cream top and skirt',
            'preview_path' => '/styles/outfits/pink-rose-blazer-with-cream-top-and-skirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'camel-overcoat-men',
            'name' => 'abrigo largo camel',
            'prompt' => 'wearing a camel overcoat',
            'preview_path' => '/styles/outfits/camel-overcoat-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-floral-button-up-blouse-women',
            'name' => 'blusa negra de botones con estampado floral',
            'prompt' => 'wearing a black floral button-up blouse',
            'preview_path' => '/styles/outfits/black-floral-button-up-blouse-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-scrub-top-and-white-lab-coat-men',
            'name' => 'uniforme médico: top azul claro y bata blanca',
            'prompt' => 'wearing a light blue scrub top and white lab coat',
            'preview_path' => '/styles/outfits/light-blue-scrub-top-and-white-lab-coat-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-blue-scrub-top-and-white-lab-coat-women',
            'name' => 'uniforme médico: top azul claro y bata blanca',
            'prompt' => 'wearing a light blue scrub top and white lab coat',
            'preview_path' => '/styles/outfits/light-blue-scrub-top-and-white-lab-coat-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'red-knitted-sweater-men',
            'name' => 'suéter rojo tejido',
            'prompt' => 'wearing a red knitted sweater',
            'preview_path' => '/styles/outfits/red-knitted-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'red-knitted-sweater-women',
            'name' => 'suéter rojo tejido',
            'prompt' => 'wearing a red knitted sweater',
            'preview_path' => '/styles/outfits/red-knitted-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'bright-red-blazer-women',
            'name' => 'saco rojo brillante',
            'prompt' => 'wearing a bright red blazer',
            'preview_path' => '/styles/outfits/bright-red-blazer-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-sleeveless-turtleneck-women',
            'name' => 'cuello tortuga negro sin mangas',
            'prompt' => 'wearing a black sleeveless turtleneck',
            'preview_path' => '/styles/outfits/black-sleeveless-turtleneck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-button-down-shirt-men',
            'name' => 'camisa azul marino de botones',
            'prompt' => 'wearing a navy button down shirt',
            'preview_path' => '/styles/outfits/navy-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-midi-fitted-dress-women',
            'name' => 'vestido negro ajustado midi',
            'prompt' => 'wearing a black midi fitted dress',
            'preview_path' => '/styles/outfits/black-midi-fitted-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-cream-graphic-hoodie-men',
            'name' => 'sudadera crema con estampado',
            'prompt' => 'wearing a light cream graphic hoodie',
            'preview_path' => '/styles/outfits/light-cream-graphic-hoodie-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-cream-graphic-hoodie-women',
            'name' => 'sudadera crema con estampado',
            'prompt' => 'wearing a light cream graphic hoodie',
            'preview_path' => '/styles/outfits/light-cream-graphic-hoodie-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'green-blazer-over-ivory-shirt-women',
            'name' => 'saco verde sobre camisa marfil',
            'prompt' => 'wearing a green blazer over ivory shirt',
            'preview_path' => '/styles/outfits/green-blazer-over-ivory-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-twist-waist-sleeveless-dress-women',
            'name' => 'vestido blanco sin mangas con cintura drapeada',
            'prompt' => 'wearing a white twist-waist sleeveless dress',
            'preview_path' => '/styles/outfits/white-twist-waist-sleeveless-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'cream-long-sleeve-henley-men',
            'name' => 'henley crema de manga larga',
            'prompt' => 'wearing a cream long-sleeve henley',
            'preview_path' => '/styles/outfits/cream-long-sleeve-henley-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'cream-long-sleeve-henley-women',
            'name' => 'henley crema de manga larga',
            'prompt' => 'wearing a cream long-sleeve henley',
            'preview_path' => '/styles/outfits/cream-long-sleeve-henley-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-denim-shirt-men',
            'name' => 'camisa de mezclilla azul claro',
            'prompt' => 'wearing a light blue denim shirt',
            'preview_path' => '/styles/outfits/light-blue-denim-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'teal-blazer-over-white-v-neck-women',
            'name' => 'saco verde azulado sobre v-neck blanco',
            'prompt' => 'wearing a teal blazer over white v-neck',
            'preview_path' => '/styles/outfits/teal-blazer-over-white-v-neck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'longsleeve-navy-blue-polo-shirt-men',
            'name' => 'polo azul marino de manga larga',
            'prompt' => 'wearing a longsleeve navy blue polo shirt',
            'preview_path' => '/styles/outfits/longsleeve-navy-blue-polo-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'longsleeve-navy-blue-polo-shirt-women',
            'name' => 'polo azul marino de manga larga',
            'prompt' => 'wearing a longsleeve navy blue polo shirt',
            'preview_path' => '/styles/outfits/longsleeve-navy-blue-polo-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-grey-button-down-shirt-men',
            'name' => 'camisa gris claro de botones',
            'prompt' => 'wearing a light grey button down shirt',
            'preview_path' => '/styles/outfits/light-grey-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-lab-coat-with-black-outfit-men',
            'name' => 'bata blanca con conjunto negro',
            'prompt' => 'wearing a white lab coat with black outfit',
            'preview_path' => '/styles/outfits/white-lab-coat-with-black-outfit-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-lab-coat-with-black-outfit-women',
            'name' => 'bata blanca con conjunto negro',
            'prompt' => 'wearing a white lab coat with black outfit',
            'preview_path' => '/styles/outfits/white-lab-coat-with-black-outfit-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-long-sleeve-v-neck-men',
            'name' => 'v-neck negro de manga larga',
            'prompt' => 'wearing a black long-sleeve v-neck',
            'preview_path' => '/styles/outfits/black-long-sleeve-v-neck-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-cap-sleeve-dress-women',
            'name' => 'vestido azul marino con mangas cap',
            'prompt' => 'wearing a navy cap sleeve dress',
            'preview_path' => '/styles/outfits/navy-cap-sleeve-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'cream-short-sleeve-polo-men',
            'name' => 'polo crema de manga corta',
            'prompt' => 'wearing a cream short-sleeve polo',
            'preview_path' => '/styles/outfits/cream-short-sleeve-polo-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-shirt-dress-with-brown-belt-women',
            'name' => 'vestido camisa blanco con cinturón marrón',
            'prompt' => 'wearing a white shirt dress with brown belt',
            'preview_path' => '/styles/outfits/white-shirt-dress-with-brown-belt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-blue-short-sleeve-button-down-men',
            'name' => 'camisa azul claro de manga corta',
            'prompt' => 'wearing a light blue short-sleeve button-down',
            'preview_path' => '/styles/outfits/light-blue-short-sleeve-button-down-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-blue-short-sleeve-button-down-women',
            'name' => 'camisa azul claro de manga corta',
            'prompt' => 'wearing a light blue short-sleeve button-down',
            'preview_path' => '/styles/outfits/light-blue-short-sleeve-button-down-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-square-neck-sheath-women',
            'name' => 'vestido negro de cuadrado',
            'prompt' => 'wearing a black square-neck sheath',
            'preview_path' => '/styles/outfits/black-square-neck-sheath-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'blue-scrub-set-men',
            'name' => 'conjunto de uniforme médico azul',
            'prompt' => 'wearing a blue scrub set',
            'preview_path' => '/styles/outfits/blue-scrub-set-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'blue-scrub-set-women',
            'name' => 'conjunto de uniforme médico azul',
            'prompt' => 'wearing a blue scrub set',
            'preview_path' => '/styles/outfits/blue-scrub-set-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-textured-sweatshirt-men',
            'name' => 'sudadera gris claro texturizada',
            'prompt' => 'wearing a light gray textured sweatshirt',
            'preview_path' => '/styles/outfits/light-gray-textured-sweatshirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-gray-textured-sweatshirt-women',
            'name' => 'sudadera gris claro texturizada',
            'prompt' => 'wearing a light gray textured sweatshirt',
            'preview_path' => '/styles/outfits/light-gray-textured-sweatshirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'cream-short-sleeve-top-women',
            'name' => 'top crema de manga corta',
            'prompt' => 'wearing a cream short-sleeve top',
            'preview_path' => '/styles/outfits/cream-short-sleeve-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-beige-blazer-and-tan-trousers-ensemble-women',
            'name' => 'conjunto de saco beige claro y pantalones beige',
            'prompt' => 'wearing a light beige blazer and tan trousers ensemble',
            'preview_path' => '/styles/outfits/light-beige-blazer-and-tan-trousers-ensemble-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'muted-mustard-blazer-with-white-boat-neck-women',
            'name' => 'saco mostaza con cuello barco blanco',
            'prompt' => 'wearing a muted mustard blazer with white boat-neck',
            'preview_path' => '/styles/outfits/muted-mustard-blazer-with-white-boat-neck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-scrub-set-men',
            'name' => 'conjunto de uniforme médico azul marino',
            'prompt' => 'wearing a navy scrub set',
            'preview_path' => '/styles/outfits/navy-scrub-set-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-scrub-set-women',
            'name' => 'conjunto de uniforme médico azul marino',
            'prompt' => 'wearing a navy scrub set',
            'preview_path' => '/styles/outfits/navy-scrub-set-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-t-shirt-and-black-joggers-men',
            'name' => 'camiseta blanca y joggers negros',
            'prompt' => 'wearing a white t-shirt and black joggers',
            'preview_path' => '/styles/outfits/white-t-shirt-and-black-joggers-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'sage-button-down-shirt-men',
            'name' => 'camisa de botones verde salvia',
            'prompt' => 'wearing a sage button down shirt',
            'preview_path' => '/styles/outfits/sage-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'soft-pink-overcoat-women',
            'name' => 'abrigo rosa claro',
            'prompt' => 'wearing a soft pink overcoat',
            'preview_path' => '/styles/outfits/soft-pink-overcoat-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'beige-long-sleeve-turtleneck-women',
            'name' => 'cuello tortuga beige de manga larga',
            'prompt' => 'wearing a beige long-sleeve turtleneck',
            'preview_path' => '/styles/outfits/beige-long-sleeve-turtleneck-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'army-green-button-down-shirt-men',
            'name' => 'camisa de botones verde militar',
            'prompt' => 'wearing an army green button down shirt',
            'preview_path' => '/styles/outfits/army-green-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-gray-cropped-t-shirt-men',
            'name' => 'camiseta gris claro corta',
            'prompt' => 'wearing a light gray cropped t-shirt',
            'preview_path' => '/styles/outfits/light-gray-cropped-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-blue-sleeveless-dress-women',
            'name' => 'vestido azul claro sin mangas',
            'prompt' => 'wearing a light blue sleeveless dress',
            'preview_path' => '/styles/outfits/light-blue-sleeveless-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-shearling-jacket-women',
            'name' => 'chaqueta negra de piel de oveja',
            'prompt' => 'wearing a black shearling jacket',
            'preview_path' => '/styles/outfits/black-shearling-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-notch-neck-a-line-women',
            'name' => 'vestido negro a-line con cuello en v',
            'prompt' => 'wearing a black notch-neck a-line dress',
            'preview_path' => '/styles/outfits/black-notch-neck-a-line-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'red-cinched-waist-dress-women',
            'name' => 'vestido rojo con cintura entallada',
            'prompt' => 'wearing a red cinched waist dress',
            'preview_path' => '/styles/outfits/red-cinched-waist-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'green-button-down-shirt-men',
            'name' => 'camisa de botones verde',
            'prompt' => 'wearing a green button down shirt',
            'preview_path' => '/styles/outfits/green-button-down-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'brown-cable-knit-turtleneck-men',
            'name' => 'cuello tortuga marrón de punto grueso',
            'prompt' => 'wearing a brown cable-knit turtleneck',
            'preview_path' => '/styles/outfits/brown-cable-knit-turtleneck-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'brown-puffer-jacket-women',
            'name' => 'chaqueta acolchada marrón',
            'prompt' => 'wearing a brown puffer jacket',
            'preview_path' => '/styles/outfits/brown-puffer-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-olive-green-blazer-men',
            'name' => 'saco verde oliva oscuro',
            'prompt' => 'wearing a dark olive green blazer',
            'preview_path' => '/styles/outfits/dark-olive-green-blazer-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'blue-and-orange-plaid-shirt-men',
            'name' => 'camisa a cuadros azul y naranja',
            'prompt' => 'wearing a blue and orange plaid shirt',
            'preview_path' => '/styles/outfits/blue-and-orange-plaid-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-short-sleeve-shirt-with-green-skirt-women',
            'name' => 'camisa blanca de manga corta con falda verde',
            'prompt' => 'wearing a white short-sleeve shirt with green skirt',
            'preview_path' => '/styles/outfits/white-short-sleeve-shirt-with-green-skirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-grey-suit-without-tie-men',
            'name' => 'traje gris claro sin corbata',
            'prompt' => 'wearing a light grey suit, without tie',
            'preview_path' => '/styles/outfits/light-grey-suit-without-tie-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-grey-suit-without-tie-women',
            'name' => 'traje gris claro sin corbata',
            'prompt' => 'wearing a light grey suit, without tie',
            'preview_path' => '/styles/outfits/light-grey-suit-without-tie-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'yellow-safety-vest-with-reflective-stripes-men',
            'name' => 'chaleco amarillo de seguridad con rayas reflectantes',
            'prompt' => 'wearing a yellow safety vest with reflective stripes',
            'preview_path' => '/styles/outfits/yellow-safety-vest-with-reflective-stripes-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'yellow-safety-vest-with-reflective-stripes-women',
            'name' => 'chaleco amarillo de seguridad con rayas reflectantes',
            'prompt' => 'wearing a yellow safety vest with reflective stripes',
            'preview_path' => '/styles/outfits/yellow-safety-vest-with-reflective-stripes-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-and-white-striped-polo-men',
            'name' => 'polo a rayas negras y blancas',
            'prompt' => 'wearing a black and white striped polo',
            'preview_path' => '/styles/outfits/black-and-white-striped-polo-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-and-white-striped-polo-women',
            'name' => 'polo a rayas negras y blancas',
            'prompt' => 'wearing a black and white striped polo',
            'preview_path' => '/styles/outfits/black-and-white-striped-polo-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-green-sleeveless-dress-women',
            'name' => 'vestido verde claro sin mangas',
            'prompt' => 'wearing a light green sleeveless dress',
            'preview_path' => '/styles/outfits/light-green-sleeveless-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-a-line-dress-women',
            'name' => 'vestido azul marino en forma de a',
            'prompt' => 'wearing a navy a-line dress',
            'preview_path' => '/styles/outfits/navy-a-line-dress-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-chefs-coat-with-black-trim-men',
            'name' => 'chaqueta de chef blanca con ribete negro',
            'prompt' => 'wearing a white chef\'s coat with black trim',
            'preview_path' => '/styles/outfits/white-chefs-coat-with-black-trim-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'creamy-white-turtleneck-with-orange-stripe-women',
            'name' => 'cuello tortuga blanco cremoso con franja naranja',
            'prompt' => 'wearing a creamy white turtleneck with orange stripe',
            'preview_path' => '/styles/outfits/creamy-white-turtleneck-with-orange-stripe-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'navy-blue-crew-neck-t-shirt-men',
            'name' => 'camiseta azul marino de cuello redondo',
            'prompt' => 'wearing a navy blue crew-neck t-shirt',
            'preview_path' => '/styles/outfits/navy-blue-crew-neck-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'navy-blue-crew-neck-t-shirt-women',
            'name' => 'camiseta azul marino de cuello redondo',
            'prompt' => 'wearing a navy blue crew-neck t-shirt',
            'preview_path' => '/styles/outfits/navy-blue-crew-neck-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-short-sleeve-t-shirt-men',
            'name' => 'camiseta negra de manga corta',
            'prompt' => 'wearing a black short-sleeve t-shirt',
            'preview_path' => '/styles/outfits/black-short-sleeve-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'dark-gray-sweatshirt-men',
            'name' => 'sudadera gris oscuro',
            'prompt' => 'wearing a dark gray sweatshirt',
            'preview_path' => '/styles/outfits/dark-gray-sweatshirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-purple-v-neck-scrub-top-women',
            'name' => 'top de escote en v lila para uniforme médico',
            'prompt' => 'wearing a light purple v-neck scrub top',
            'preview_path' => '/styles/outfits/light-purple-v-neck-scrub-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'tan-leopard-print-faux-fur-jacket-women',
            'name' => 'chaqueta de imitación de piel con estampado de leopardo',
            'prompt' => 'wearing a tan leopard print faux fur jacket',
            'preview_path' => '/styles/outfits/tan-leopard-print-faux-fur-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-graduation-robe-men',
            'name' => 'toga de graduación negra',
            'prompt' => 'wearing a black graduation robe',
            'preview_path' => '/styles/outfits/black-graduation-robe-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-graduation-robe-women',
            'name' => 'toga de graduación negra',
            'prompt' => 'wearing a black graduation robe',
            'preview_path' => '/styles/outfits/black-graduation-robe-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'multicolored-striped-sweater-men',
            'name' => 'suéter a rayas multicolor',
            'prompt' => 'wearing a multicolored striped sweater',
            'preview_path' => '/styles/outfits/multicolored-striped-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'grey-t-shirt-men',
            'name' => 'camiseta gris',
            'prompt' => 'wearing a grey t-shirt',
            'preview_path' => '/styles/outfits/grey-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'grey-t-shirt-women',
            'name' => 'camiseta gris',
            'prompt' => 'wearing a grey t-shirt',
            'preview_path' => '/styles/outfits/grey-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'gray-long-sleeve-sweater-women',
            'name' => 'suéter gris de manga larga',
            'prompt' => 'wearing a gray long-sleeve sweater',
            'preview_path' => '/styles/outfits/gray-long-sleeve-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'beige-t-shirt-men',
            'name' => 'camiseta beige',
            'prompt' => 'wearing a beige t-shirt',
            'preview_path' => '/styles/outfits/beige-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'beige-t-shirt-women',
            'name' => 'camiseta beige',
            'prompt' => 'wearing a beige t-shirt',
            'preview_path' => '/styles/outfits/beige-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-pilot-shirt-with-epaulets-women',
            'name' => 'camisa blanca de piloto con charreteras',
            'prompt' => 'wearing a white pilot shirt with epaulets',
            'preview_path' => '/styles/outfits/white-pilot-shirt-with-epaulets-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'white-pilot-shirt-with-epaulets-men',
            'name' => 'camisa blanca de piloto con charreteras',
            'prompt' => 'wearing a white pilot shirt with epaulets',
            'preview_path' => '/styles/outfits/white-pilot-shirt-with-epaulets-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'brown-t-shirt-women',
            'name' => 'camiseta marrón',
            'prompt' => 'wearing a brown t-shirt',
            'preview_path' => '/styles/outfits/brown-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'brown-t-shirt-men',
            'name' => 'camiseta marrón',
            'prompt' => 'wearing a brown t-shirt',
            'preview_path' => '/styles/outfits/brown-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-leather-jacket-men',
            'name' => 'chaqueta de cuero negro',
            'prompt' => 'wearing a black leather jacket',
            'preview_path' => '/styles/outfits/black-leather-jacket-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-hooded-sweatshirt-women',
            'name' => 'sudadera blanca con capucha',
            'prompt' => 'wearing a white hooded sweatshirt',
            'preview_path' => '/styles/outfits/white-hooded-sweatshirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'beige-oversized-t-shirt-men',
            'name' => 'camiseta beige oversize',
            'prompt' => 'wearing a beige oversized t-shirt',
            'preview_path' => '/styles/outfits/beige-oversized-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'beige-oversized-t-shirt-women',
            'name' => 'camiseta beige oversize',
            'prompt' => 'wearing a beige oversized t-shirt',
            'preview_path' => '/styles/outfits/beige-oversized-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-blue-graduation-gown-women',
            'name' => 'toga de graduación azul oscuro',
            'prompt' => 'wearing a dark blue graduation gown',
            'preview_path' => '/styles/outfits/dark-blue-graduation-gown-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'teal-and-black-checkered-flannel-shirt-men',
            'name' => 'camisa de franela a cuadros verde azulado y negro',
            'prompt' => 'wearing a teal and black checkered flannel shirt',
            'preview_path' => '/styles/outfits/teal-and-black-checkered-flannel-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'longsleeve-navy-scrub-set-men',
            'name' => 'conjunto de uniforme médico azul marino manga larga',
            'prompt' => 'wearing a longsleeve navy scrub set',
            'preview_path' => '/styles/outfits/longsleeve-navy-scrub-set-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'longsleeve-navy-scrub-set-women',
            'name' => 'conjunto de uniforme médico azul marino manga larga',
            'prompt' => 'wearing a longsleeve navy scrub set',
            'preview_path' => '/styles/outfits/longsleeve-navy-scrub-set-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-off-the-shoulder-long-sleeve-top-and-high-waisted-trousers-women',
            'name' => 'top negro de manga larga caído y pantalones de tiro alto',
            'prompt' => 'wearing a black off-the-shoulder long-sleeve top and high-waisted trousers',
            'preview_path' => '/styles/outfits/black-off-the-shoulder-long-sleeve-top-and-high-waisted-trousers-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'scrubs-unpatterned-light-blue-with-white-lab-coat-overtop-men',
            'name' => 'uniforme médico: azul claro con bata blanca',
            'prompt' => 'wearing scrubs (unpatterned, light blue with white lab coat overtop)',
            'preview_path' => '/styles/outfits/scrubs-unpatterned-light-blue-with-white-lab-coat-overtop-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'scrubs-unpatterned-light-blue-with-white-lab-coat-overtop-women',
            'name' => 'uniforme médico: azul claro con bata blanca',
            'prompt' => 'wearing scrubs (unpatterned, light blue with white lab coat overtop)',
            'preview_path' => '/styles/outfits/scrubs-unpatterned-light-blue-with-white-lab-coat-overtop-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'dark-wool-overcoat-with-rib-knit-sweater-men',
            'name' => 'abrigo de lana oscuro con suéter acanalado',
            'prompt' => 'wearing a dark wool overcoat with rib-knit sweater',
            'preview_path' => '/styles/outfits/dark-wool-overcoat-with-rib-knit-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'red-t-shirt-women',
            'name' => 'camiseta roja',
            'prompt' => 'wearing a red t-shirt',
            'preview_path' => '/styles/outfits/red-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'red-t-shirt-men',
            'name' => 'camiseta roja',
            'prompt' => 'wearing a red t-shirt',
            'preview_path' => '/styles/outfits/red-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-army-green-button-up-overshirt-men',
            'name' => 'sobretodo verde militar de botones',
            'prompt' => 'wearing a light army-green button-up overshirt',
            'preview_path' => '/styles/outfits/light-army-green-button-up-overshirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'black-zip-up-nike-hoodie-men',
            'name' => 'sudadera con cremallera negra de Nike',
            'prompt' => 'wearing a black zip-up nike hoodie',
            'preview_path' => '/styles/outfits/black-zip-up-nike-hoodie-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'white-kandura-men',
            'name' => 'kandura blanca',
            'prompt' => 'wearing a white kandura',
            'preview_path' => '/styles/outfits/white-kandura-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'olive-khaki-short-sleeve-button-up-women',
            'name' => 'camisa de manga corta caqui oliva',
            'prompt' => 'wearing an olive-khaki short-sleeve button-up',
            'preview_path' => '/styles/outfits/olive-khaki-short-sleeve-button-up-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'light-gray-zip-up-hoodie-men',
            'name' => 'sudadera con cremallera gris claro',
            'prompt' => 'wearing a light gray zip-up hoodie',
            'preview_path' => '/styles/outfits/light-gray-zip-up-hoodie-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'brown-crewneck-sweatshirt-men',
            'name' => 'sudadera marrón de cuello redondo',
            'prompt' => 'wearing a brown crewneck sweatshirt',
            'preview_path' => '/styles/outfits/brown-crewneck-sweatshirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'forest-green-sleeveless-knit-top-women',
            'name' => 'top verde bosque sin mangas tejido',
            'prompt' => 'wearing a forest green sleeveless knit top',
            'preview_path' => '/styles/outfits/forest-green-sleeveless-knit-top-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'yellow-t-shirt-men',
            'name' => 'camiseta amarilla',
            'prompt' => 'wearing a yellow t-shirt',
            'preview_path' => '/styles/outfits/yellow-t-shirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'yellow-t-shirt-women',
            'name' => 'camiseta amarilla',
            'prompt' => 'wearing a yellow t-shirt',
            'preview_path' => '/styles/outfits/yellow-t-shirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'neutral-high-neck-knit-sweater-men',
            'name' => 'suéter neutro de cuello alto',
            'prompt' => 'wearing a neutral high-neck knit sweater',
            'preview_path' => '/styles/outfits/neutral-high-neck-knit-sweater-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'neutral-high-neck-knit-sweater-women',
            'name' => 'suéter neutro de cuello alto',
            'prompt' => 'wearing a neutral high-neck knit sweater',
            'preview_path' => '/styles/outfits/neutral-high-neck-knit-sweater-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'off-white-high-collared-sherpa-fleece-jacket-men',
            'name' => 'chaqueta de felpa sherpa blanco roto con cuello alto',
            'prompt' => 'wearing an off-white high-collared sherpa fleece jacket',
            'preview_path' => '/styles/outfits/off-white-high-collared-sherpa-fleece-jacket-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'off-white-high-collared-sherpa-fleece-jacket-women',
            'name' => 'chaqueta de felpa sherpa blanco roto con cuello alto',
            'prompt' => 'wearing an off-white high-collared sherpa fleece jacket',
            'preview_path' => '/styles/outfits/off-white-high-collared-sherpa-fleece-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'pastel-pink-crew-neck-sweatshirt-men',
            'name' => 'sudadera rosa pastel de cuello redondo',
            'prompt' => 'wearing a pastel-pink crew-neck sweatshirt',
            'preview_path' => '/styles/outfits/pastel-pink-crew-neck-sweatshirt-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'pastel-pink-crew-neck-sweatshirt-women',
            'name' => 'sudadera rosa pastel de cuello redondo',
            'prompt' => 'wearing a pastel-pink crew-neck sweatshirt',
            'preview_path' => '/styles/outfits/pastel-pink-crew-neck-sweatshirt-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'cream-knit-sweater-with-plaid-shirt-jacket-women',
            'name' => 'suéter crema con chaqueta de camisa a cuadros',
            'prompt' => 'wearing a cream knit sweater with plaid shirt-jacket',
            'preview_path' => '/styles/outfits/cream-knit-sweater-with-plaid-shirt-jacket-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'burnt-orange-abstract-patterned-blouse-women',
            'name' => 'blusa naranja quemado con estampado abstracto',
            'prompt' => 'wearing a burnt-orange abstract patterned blouse',
            'preview_path' => '/styles/outfits/burnt-orange-abstract-patterned-blouse-women.webp',
            'gender' => 'Female',
        ],
        [
            'slug' => 'black-jacket-with-light-gray-piping-men',
            'name' => 'chaqueta negra con ribetes gris claro',
            'prompt' => 'wearing a black jacket with light gray piping',
            'preview_path' => '/styles/outfits/black-jacket-with-light-gray-piping-men.webp',
            'gender' => 'Male',
        ],
        [
            'slug' => 'light-sea-green-button-down-with-vintage-crane-pattern-men',
            'name' => 'camisa verde mar claro con estampado de grullas vintage',
            'prompt' => 'wearing a light sea-green button-down with vintage crane pattern',
            'preview_path' => '/styles/outfits/light-sea-green-button-down-with-vintage-crane-pattern-men.webp',
            'gender' => 'Male',
        ],
    ];
}
